package xblydxj.gank.db.Meizhi;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig meizhiDaoConfig;

    private final MeizhiDao meizhiDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        meizhiDaoConfig = daoConfigMap.get(MeizhiDao.class).clone();
        meizhiDaoConfig.initIdentityScope(type);

        meizhiDao = new MeizhiDao(meizhiDaoConfig, this);

        registerDao(Meizhi.class, meizhiDao);
    }
    
    public void clear() {
        meizhiDaoConfig.getIdentityScope().clear();
    }

    public MeizhiDao getMeizhiDao() {
        return meizhiDao;
    }

}
