package xblydxj.gank.db.Meizhi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEIZHI".
 */
public class Meizhi {

    private Long id;
    private String time;
    private String url;

    public Meizhi() {
    }

    public Meizhi(Long id) {
        this.id = id;
    }

    public Meizhi(Long id, String time, String url) {
        this.id = id;
        this.time = time;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
