package xblydxj.gank.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATA_CATCH".
 */
public class dataCatch {

    private Long id;
    private String desc;
    private String time;
    private String author;
    private String url;
    private String type;

    public dataCatch() {
    }

    public dataCatch(Long id) {
        this.id = id;
    }

    public dataCatch(Long id, String desc, String time, String author, String url, String type) {
        this.id = id;
        this.desc = desc;
        this.time = time;
        this.author = author;
        this.url = url;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
